language: python
dist: xenial
sudo: required
cache: pip
matrix:
  include:
    - python: 3.7
    - python: 3.8-dev
    - python: nightly
  # because of psycopg2 build error:
  # psycopg/psycopgmodule.c:689:18: error: dereferencing pointer to incomplete type ‘PyInterpreterState {aka struct _is}’
  allow_failures:
    - python: 3.8-dev
    - python: nightly
before_script:
  - sudo -u postgres psql < ci/create_database.sql
before_install:
  # depends
  - pip install aiopg

  # test depends
  - pip install mypy
  - pip install flake8
  - pip install flake8-builtins!=1.1.0
  - pip install flake8-import-order
  - pip install flake8-quotes
script:
  - make flake8
  - make mypy
