language: python
dist: focal
sudo: required
cache: pip
services:
  - postgresql
matrix:
  include:
    - python: 3.8
      env: COVERAGE=yes
    - python: 3.9-dev
    - python: nightly
  allow_failures:
    - python: nightly
before_install:
  - pip install coveralls
  - pip install -r requirements-dev.txt
before_script:
  - sudo -u postgres psql < ci/create_database.sql
script:
  - make flake8
  - make mypy
  - COVERAGE_FILE=.coverage.tst coverage run --source=linkchecker -m unittest discover
  - COVERAGE_FILE=.coverage.run coverage run --source=repology-linkchecker,linkchecker repology-linkchecker.py --dsn "dbname=repology user=repology password=repology" --single-run
  - coverage combine
  - psql -U repology -x -c 'SELECT * FROM links'
after_success:
  - if [ -n "$COVERAGE" ]; then coveralls; fi
