#
# per-host overrides
#
github.com: { delay: 1 }
github.io: { delay: 1, aggregate: true }
notabug.org: { delay: 60 }
npmjs.com: { delay: 10 }
npmjs.org: { delay: 10 }
sf.net: { aggregate: true }
sourceforge.net: { aggregate: true }

#
# blacklist
#

# redirects to https://www.bestsevenreviews.com/best-linux-distros/ garbage
mepis.org: { blacklist: true }

# overtaken over by some iPhone Photography Equipment crap
qtoctave.wordpress.com: { blacklist: true }

# domain for sale
nimuh.com: { blacklist: true }

# overtaken by some game
astroid.org: { blacklist: true }

# overtaken by some french vpn "securify" garbage
dejavu-fonts.org: { blacklist: true }

# overtaken by some japanese company
opentnl.org: { blacklist: true }

# overtaken by some japanese health company
ofset.org: { blacklist: true }

# overtaken
konst.org.ua: { blacklist: true }
thekonst.net: { blacklist: true }
topfx.com: { blacklist: true }
tkzinc.org: { blacklist: true }
gnugadu.org: { blacklist: true }
junoplay.com: { blacklist: true }
conduit-project.org: { blacklist: true }
cross-pcg.com: { blacklist: true }
coolreader.org: { blacklist: true }
opensync.org: { blacklist: true }
wmii.de: { blacklist: true }
libcapn.org: { blacklist: true }
aseman.co: { blacklist: true }
ferite.org: { blacklist: true }
